services:

  db:
    image: 'db-product:latest'
    container_name: db-product
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      #- POSTGRES_DB=productdb

