server:
  port: 9300

spring:
  application:
    name: bidding-query-service
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:h2:mem:biddingquerydb
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console.enabled: true

eureka:
  client.serviceUrl.defaultZone: http://localhost:8761/eureka
  instance.hostname: localhost

spring.cloud.stream:
  function:
    definition: biddingProcessor
  # Processors
  bindings:
    biddingProcessor-in-0:
      destination: bid-created-testtest
    biddingProcessor-out-0:
      destination: product-store-testtest
  kafka:
    streams:
      binder:
        applicationId: bidding-query-service
        configuration:
          spring.json.trusted.packages: '*'
          #schema.registry.url: http://localhost:8081
          #commit.interval.ms: 100
          default:
            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            value.serde: org.springframework.kafka.support.serializer.JsonSerde
